return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		local configs = require("nvim-treesitter.configs")

		configs.setup({
			ensure_installed = {
				"bash",
				"c",
				"clojure",
				"cmake",
				"csv",
				"diff",
				"dockerfile",
				"gitcommit",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitignore",
				"go",
				"goctl",
				"graphql",
				"haskell",
				"html",
				"http",
				"hyprlang",
				"ini",
				"javascript",
				"json",
				"jsonc",
				"latex",
				"lua",
				"make",
				"markdown",
				"norg",
				"perl",
				"php",
				"python",
				"query",
				"r",
				"regex",
				"rust",
				"scala",
				"soql",
				"sql",
				"ssh_config",
				"terraform",
				"tmux",
				"toml",
				"typescript",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
				"zig",
			},
			sync_install = false,
			auto_install = true,
			highlight = { enable = true, additional_vim_regex_highlighting = false },
			indent = { enable = true },
		})
	end,
}
