[colors]
foreground = "#EEE8D5"
background = "#00141A"
cursor_bg = "#FFFFFF"
cursor_border = "#FFFFFF"
cursor_fg = "#EEE8D5"
selection_bg = "#FDF6E3"
selection_fg = "#00141A"

ansi = ["#073642", "#332700", "#5C220A", "#57100F", "#25285B", "#103956", "#103B3D", "#2C3300"]   
brights = ["#FFE999", "#FF9468", "#FF9D9B", "#FF77B9", "#CCCFFF", "#AADCFF", "#B9FFFA", "#D6FFAC"]


[colors.tab_bar]
inactive_tab_edge = "#1e2030"
background = "#191b28"

[colors.tab_bar.active_tab]
fg_color = "#82aaff"
bg_color = "#222436"

[colors.tab_bar.inactive_tab]
bg_color = "#1e2030"
fg_color = "#545c7e"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1e2030"
fg_color = "#82aaff"

[colors.tab_bar.new_tab_hover]
fg_color = "#1e2030"
bg_color = "#82aaff"

[colors.tab_bar.new_tab]
fg_color = "#82aaff"
bg_color = "#191b28"

[metadata]
aliases = []
author = "craftzdog"
name = "Solarized Osaka Base"
